stages:
  - testing


image: continuumio/miniconda3:latest


default:
  tags:
    - tomrunner


before_script:
  - conda env create --file=environment.yml
  - conda init bash
  - source ~/.bashrc
  - conda activate survival_tests


autotest:
  stage: testing
  script:
    - coverage run -m pytest ./survival_tests/tests/test_*.py
    - coverage report -m
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
